name: Test
on:
  pull_request:
  merge_group:
  push:
    paths:
      - "**.go"
    branches:
      - v0.38.x-celestia
      - main

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
            Makefile
      - name: Run Go Tests
        run: |
          make test
        if: env.GIT_DIFF
      - name: Run Go Race tests
        run: |
          make test_race
        if: env.GIT_DIFF
